# See http://doc.gitlab.com/ce/ci/yaml/ for documentation.
Build and Check (x86-64):
  script:
  - git submodule update --init && make autoreconf && ./configure --disable-doc && make -j4 && make -j4 check
  except:
  - tags
  tags:
  - x86-64
Build and Check (x86):
  script:
  - git submodule update --init && make autoreconf && ./configure --disable-doc && make -j4 && make -j4 check
  except:
  - tags
  tags:
  - x86
Build and Check with asan:
  script:
  - git submodule update --init && make autoreconf && CFLAGS="-fsanitize=address -g
    -O2" LDFLAGS="-static-libasan" ./configure --disable-doc --disable-valgrind-tests && make -j4 && make check -j4
  except:
  - tags
Build and Check with ubsan:
  script:
  - git submodule update --init && make autoreconf && CFLAGS="-fsanitize=undefined -fno-sanitize-recover -g
    -O2" LDFLAGS="-static-libubsan" ./configure --disable-doc --disable-valgrind-tests && make -j4 && make check -j4
  tags:
  - ubsan
  except:
  - tags
